export const sTextaPackageName = "texta";
export { TextaValidationError, throwTextaValidationError } from "./errors.js";
export { validateAttributedTextValue } from "./invariants.js";
export { convertICodePointToIUtf16, convertIGraphemeToIUtf16, convertIUtf16ToICodePoint, convertIUtf16ToIGrapheme, detectRgStorageMode, getRgCodePointBoundaryUtf16, getRgGraphemeBoundaryUtf16, getRgGraphemeSegment } from "./segmentation.js";
export { cleanupUnreferencedStyles, computeStyleHash, createStyleDictionaryState, createStyleDictionaryStateFromEntries, getStyleRefCount, getStyleEntryById, internStyleEntry, releaseStyleId, retainStyleId, normalizeStyleEntry, stringifyNormalizedStyleEntry } from "./dictionary.js";
export { applyStyle, getRgStyleRun } from "./style-ops.js";
export { deleteTextRange, insertText, replaceTextRange } from "./text-ops.js";
export { transformSemanticToRender, createThemingCache, transformSemanticToRenderWithCache } from "./theming.js";
export { getRenderBridgeSpan, getRgRenderBridgeRun, getRgRenderDecorationRange, getRgRenderBridgeBoundaryUtf16, convertRenderBridgeIUnitToIUtf16, convertRenderBridgeIUtf16ToIUnit } from "./render-bridges.js";
export { getTextaBaselineBenchmarkScenario, runBenchmarkScenario, runTextaBaselineBenchmark } from "./benchmark.js";
export { rgTextaDefaultBenchmarkThreshold, evaluateBenchmarkThreshold, formatBenchmarkThresholdReportMarkdown } from "./benchmark-thresholds.js";
